canonical/prometheus-k8s-operator

README.md

Added more instructions in the readme file

Updated readme with simple instructions

---

README.md
src/charm.py

Fix some trivial typos in charm.py and README.md

Fix some trivial typos

---

tests/test_charm.py

Include expected logs in tests and avoid polluting test output with logs

Include expected logs in tests and avoid polluting test output with logs

---

.gitignore

Ignore some files from git

---

README.md
config.yaml
metadata.yaml
run_tests
src/charm.py
tests/test_charm.py

Review changes as requested by @jlounder

Implemented review changes

---

metadata.yaml

This is a change required by Grafana.

Grafana-source relation interface name change

---

src/charm.py

This commit removes an extra blank line.

Remove extra blank line

---

config.yaml
src/charm.py
tests/test_charm.py

This commit adds support for custom Prometheus scrape configurations.

Support custom scrape configuration

---

README.md
config.yaml
lib/charms/prometheus/v1/prometheus.py
metadata.yaml
requirements.txt
run_tests
src/charm.py
src/prometheus_provider.py
src/prometheus_server.py
tests/test_charm.py
tests/test_lib.py
tests/test_provider.py
tests/test_server.py

This pull request provides
1. An first version of the prometheus operator after migration to Pebble
2. An basic Prometheus provider/consumer charm library the accept scrape targets over relation data.

Charm libs

---

run_tests
src/charm.py
tests/test_lib.py

1. Fix two timing bugs (mentioned in commit message)
2. Small refactor of names and methods to isolate configuration of Prometheus into a separate function that is not an event handler.
3. Fix import statement in charm library unit test

Fix two bugs with other small refactors

---

src/charm.py

fix config_hash calculation

---

.github/workflows/run_tests.yaml

Added github unit test running

---

lib/charms/prometheus_k8s/v1/prometheus.py
run_tests
src/charm.py
src/prometheus_provider.py
src/prometheus_server.py
tests/test_charm.py
tests/test_lib.py
tests/test_provider.py
tests/test_server.py

Linting cleanups
1.  Added option for automated linting clean-up using black
2. Ran black and committed all linting clean-ups (almost all conversion of single quote to double)

Linting Cleanup

---

src/charm.py
tests/test_charm.py

Update the prometheus charm to use smarter data bags instead of dumping a raw dict into the relation

Make the prometheus charm use a better Grafana interface

---

metadata.yaml

namespace interfaces with underscore

---

.flake8
lib/charms/grafana_k8s/v0/grafana_source.py
lib/charms/grafana_k8s/v1/grafana_source.py
src/charm.py
tests/test_charm.py

Add the Grafana consumer library and use that to set data on the data bucket instead of doing it directly. Update the tests to match

Use a Grafana consumer library instead of raw relation data 

---

.flake8
charmcraft.yaml
lib/charms/prometheus_k8s/v0/prometheus.py
run_tests
tests/test_consumer.py
tests/test_provider.py

Added unit tests for recent enhancements to Prometheus charm library and fixes a couple of bugs with those enhancements.

Unit tests

---

lib/charms/alertmanager_k8s/v0/alertmanager.py
src/charm.py
tests/test_charm.py

Updates to prometheus, to go with corresponding [changes in alertmanager](https://github.com/canonical/alertmanager-operator/pull/7).

better interface with alertmanager

---

lib/charms/grafana_k8s/v1/grafana_source.py

Sync up with what got merged into `canonical:grafana-operator` after review

Sync Grafana juju topology with parent merge

---

lib/charms/alertmanager_k8s/v0/alertmanager.py

Following up on https://github.com/canonical/alertmanager-operator/pull/23

update alertmanager lib

---

INTEGRATING.md
lib/charms/prometheus_k8s/v0/prometheus.py

Small improvements
1. A little more details in INTEGRATION.md
2. Bump library patch level.

Few cleanups

---

README.md
charmcraft.yaml
lib/charms/nginx_ingress_integrator/v0/ingress.py
metadata.yaml
src/charm.py
tests/test_charm.py

Uses the nginx-ingress-integrator charm v0 ingress library to add an
ingress relation to the charm.
Issue: https://github.com/canonical/prometheus-operator/issues/25

Add ingress relation

---

src/charm.py

This commit replace the obsolete container.is_ready() API
with the container.can_connect() method. It is just a single
line change despite appearences, because all the code that
was previously nested in the context manager is now unindented
one level but guarded with the can_connect() method.

Switched to new container can connect API

---

lib/charms/alertmanager_k8s/v0/alertmanager_dispatch.py
src/charm.py

See https://github.com/canonical/alertmanager-operator/pull/36

fetch-lib alertmanager_dispatch

---

lib/charms/prometheus_k8s/v0/prometheus_scrape.py
src/charm.py
tests/test_endpoint_consumer.py
tests/test_endpoint_provider.py

This PR enhances the Prometheus charm library to support additional scrape configuration options.

Additional Scrape configuration options

---

lib/charms/prometheus_k8s/v0/prometheus_scrape.py

This commit refactors the logic of MetricsEndpointProvider to
do two addtional things
1. Ensure that scrape job information is update when the metrics
endpoint provider charm is upgraded.
2. Ensure that all related metrics endpoint consumer charms are
notified of any changes in scrape job information.
Closes #109

Handle upgrade event and multiple consumers

---

src/charm.py

This commit ensures that blocked status is set on failure to
reload Prometheus configuration
Closes #105

Check return value for configuration reload

---

lib/charms/prometheus_k8s/v0/prometheus_scrape.py
tox.ini

Note: @balbirthomas I converted `JujuTopology` from a dataclass to a regular class. Tests still pass but I wanted to bring that to your attention.

support python 3.5 in libs

---

config.yaml
lib/charms/prometheus_k8s/v0/prometheus_scrape.py
src/charm.py
tests/unit/test_charm.py
tests/unit/test_endpoint_consumer.py
tests/unit/test_endpoint_provider.py
tox.ini

- Updated Library overview docs to reflect recent changes made to the interface
- Set unit names in relation data
- Updated unit tests to reflect unit names are present in relation data
- Correct docstrings of individual methods
Deferred to future PRs.
- Review of test cases and perhaps add more unit tests
- Other code cleanups (such as refactor of rules provider and related objects for which github tickets have been created).

Minor updates and code cleanups

---

tests/integration/test_kubectl_delete.py
tests/integration/test_upgrade_charm.py

This PR adds kubectl itests for spotting the various edge cases @mmanciop is repeatedly finding manually.

add kubectl tests

---

requirements.txt
tests/integration/prometheus-tester/requirements.txt
tests/integration/test_kubectl_delete.py
tests/integration/test_upgrade_charm.py

- Update to secured git Python requirements
- Add note and link to github issue that some integration tests may sporadically fail.

Minor fixes

---

.gitignore
lib/charms/alertmanager_k8s/v0/alertmanager_dispatch.py
lib/charms/grafana_k8s/v0/grafana_source.py
lib/charms/observability_libs/v0/kubernetes_service_patch.py
lib/charms/prometheus_k8s/v0/prometheus_remote_write.py
metadata.yaml
pyproject.toml
requirements.txt
src/charm.py
tests/integration/conftest.py
tests/integration/helpers.py
tests/integration/prometheus-tester/src/metrics.py
tests/integration/test_charm.py
tests/integration/test_remote_write.py
tests/integration/test_upgrade_charm.py
tests/integration/workload.py
tests/unit/test_charm.py
tests/unit/test_endpoint_provider.py
tests/unit/test_remote_write.py
tox.ini

Implement a Prometheus `remote_write` library with all expected bells and whistles :-)

Prometheus remote_write library

---

lib/charms/prometheus_k8s/v0/prometheus_scrape.py

This commit updates the lib patch number for the Prometheus
scrape library.

Updated libpatch number for prometheus library

---

lib/charms/prometheus_k8s/v0/prometheus_remote_write.py
lib/charms/prometheus_k8s/v0/prometheus_scrape.py
tests/unit/test_transform.py

verify and solve #223 with unit tests and disabling shell mode

---

metadata.yaml

This commit updates this charms documentation in preparation of
publishing it on discourse.

Updated docs for discourse

---

CONTRIBUTING.md

Docs around promql-transform are slightly lacking.
Users could certainly figure it out on their own but this inclusion might offer a better first impression.
Add in leftovers from #241.
NTA.
Run the newly added commands locally to make sure it works. (it does :)
Add pasteable commands for promql-transform.

[doc] Add pasteable commands for promql-transform

---

lib/charms/prometheus_k8s/v0/prometheus_scrape.py

Remove ProviderTopology.from_charm(charm)

---

CONTRIBUTING.md
README.md

The deploy commands in README.md and CONTRIBUTING.md need to be updated
Update the docs
-
-
-

add --trust in sample commands

---

src/charm.py
src/utils.py
tests/integration/test_rerelate.py
tests/unit/test_charm.py
tox.ini

Charm class is starting to become quite long and messy.
- Restructure and clean up some of the charm code.
- Remove superfluous inline comments.
- Extract a dangling function to its own file.
N/A
Run the CI. There should be no behavioral changes. 
Do some housekeeping in the Prometheus charm class.

clean up charm class

---

tests/integration/test_rerelate.py
tox.ini

While it is unlikely to matter, this pin could possibly pose issues.
change to "<"
None?
None

make the pin a little bit better

---

tests/unit/test_charm.py
tests/unit/test_endpoint_aggregator.py
tests/unit/test_endpoint_consumer.py
tests/unit/test_endpoint_provider.py
tests/unit/test_prometheus_rules_provider.py
tests/unit/test_remote_write.py
tests/unit/test_transform.py

* remove patch for UUID and replace with uuid v4 real value
* remove duplicated test. @sed-i, please check it, comments look different, but the code itself is identical

cleanup tests

---

tests/unit/test_endpoint_consumer.py
tests/unit/test_endpoint_provider.py

now all the tests could be executed from any folder

make all tests to be independent of invocation folder

---

.github/workflows/update-libs.yaml
lib/charms/grafana_k8s/v0/grafana_dashboard.py
lib/charms/observability_libs/v1/kubernetes_service_patch.py
src/charm.py
tests/unit/test_remote_write.py

There's an ongoing problem with libraries not being pushed after merging to `main` nor being fetched when they become outdated.
This PR aims at partially tackling this issue, by periodically checking the library status and creating PRs to update them when necessary.
The modifications are mainly additions and improvements on the CI for the aforementioned purpose.

Add update-libs CI to prometheus

---

metadata.yaml

remove doc line from metadata.yaml

---

README.md
metadata.yaml

Use a ROCK image from GHCR instead of Launchpad

Use a ROCK image

---

tox.ini

Address the comments made in #448.

fix version bump check

---

lib/charms/observability_libs/v0/juju_topology.py
lib/charms/prometheus_k8s/v0/prometheus_remote_write.py
tox.ini

This PR fixes #378 (docstrings)

Remove %%juju_topology%% from remote-write docstrings

---

tests/integration/test_external_url.py

Some itests have issues.
Fix the issues.
Fixes #416.
The re-relate test was dropped in #463.
Fix some itests.

Fix some itests

---

lib/charms/tempo_k8s/v0/charm_instrumentation.py
lib/charms/tempo_k8s/v0/tracing.py
lib/charms/traefik_k8s/v1/ingress_per_unit.py
metadata.yaml
requirements.txt
src/charm.py
tests/scenario/test_server_scheme.py
tox.ini

Lining up this PR towards https://github.com/canonical/tempo-k8s-operator/pull/35
Flip tracing direction.

Flip tracing direction

---

.gitignore
lib/charms/tempo_k8s/v0/charm_tracing.py
src/charm.py
tests/scenario/helpers.py
tox.ini

charm_instrumentation has been replaced by charm_tracing
also freshened up the scenario tox ini

Swap charm tracing libs

---

lib/charms/alertmanager_k8s/v1/alertmanager_dispatch.py
lib/charms/tempo_k8s/v0/tracing.py
src/charm.py

Occasional code ordering issue where ingress reqs are updated before the cert is written, resulting in http instead of https.
Move update methods into `_configure`.
Fixes #533.
Drive-by fixes:
- fetch-lib.
Run integration tests from https://github.com/canonical/cos-lite-bundle/pull/80.

Update ingress after cert is written

---

src/charm.py

Prometheus was reporting its external url to grafana.
This could entail DNS, TLS or NAT hairpinning.
https://chat.charmhub.io/charmhub/pl/d1t9wb9i1i8d3qpeui76e9zk1h
Use the internal URL until https://github.com/canonical/operator/issues/970 is fixed.

Use internal url for grafana source

---

charmcraft.yaml
lib/charms/prometheus_k8s/v0/prometheus_scrape.py
lib/charms/prometheus_k8s/v1/prometheus_remote_write.py
tests/integration/helpers.py

Needed for the following PR: https://github.com/canonical/grafana-agent-operator/pull/231
More info on the CIS hardening rule can be found here[^1].
Use `path.chmod(0o775)` in order to comply wit the CIS Hardening rules.
[^1]: https://github.com/canonical/grafana-agent-operator/issues/208

fix: update cos-tool permissions to adhere to cis hardening rules

---

src/charm.py

Previously, PrometheusCharm.external_url returned the external url if it was available, otherwise it returned the ingress url. This meant that any consuming code that explicitly wanted the external_url or nothing needed to duplicate checks that exist in external_url, making it easy to later have these go out of sync.
This change breaks external_url into two functions:
* external_url, which explicitly returns only an external url or None (if it isn't available)
* most_external_url, which returns the external_url if it is available, otherwise the internal url
This is useful for a planned future PR which will need exactly the external_url
none
change is covered by existing unit tests
no effect

refactor: refactor: change PrometheusCharm.external_url, add most_external_url
