- src/charm.py
Two minor fixes here. If we are setting blocked status, we need to make sure we return so it doesn't get changed back. Also, the status was set twice.
> Fix blocked state

- src/charm.py
- tests/test_charm.py
This commit fixes a typo that resulted from the recent merge
of alertmanager support commit. The stored state variable
should be named "_stored" but was instead "stored".
> Fix incorrect label for stored state

- README.md
- config.yaml
- metadata.yaml
- requirements.txt
- src/charm.py
- tests/test_charm.py
1. Removing support for adding a Prometheus configuration using Juju command line. Also updated README accordingly.
2. Minor grammatical and spelling fixes.
> Revert scrape config

- lib/charms/prometheus/v1/prometheus.py
This commit removes a redundant ternary operator that
was left over from an early development version of the
code and overlooked.
> Default http port is not special

- src/charm.py
- tests/test_charm.py
This change removes any concern of Alertmanager's API port from the prometheus operator.
The prometheus operator should not concern itself with concatenating Alertmanager's API port because:
1. Alertmanager is perfectly capable of concatenating the port to the address on its own.
2. In the most general case, the Alertmanager API port may vary across replicas, and the current implementation in prometheus expects a scalar for `port`, not a vector or mapping.
> remove concat of alertmanager api port

- README.md
- metadata.yaml
This commit changes the name of the charm to confirm with the
standard for Kubernetes charms. Also the readme file is updated
to add deployment instructions.
> Updated charm name with deployment instructions

- actions.yaml
- actions/reload-config
- config.yaml
- src/charm.py
- tests/test_charm.py
1. Remove now redundant image username and password
2. Remove redundant check config
3. Remove redundant action
4. Remove unimplemented ssl cert and key
closes https://github.com/canonical/prometheus-operator/issues/45 https://github.com/canonical/prometheus-operator/issues/43
> Removing unused code

- .gitignore
- metadata.yaml
- requirements-dev.txt
- run_tests
The charmcraft init template now includes coverage, update this charm to include that.
Also add a "display-name" in metadata.yaml so the name of the charm is correctly displayed on https://charmhub.io
> Add coverage to tests, add display-name for nicer display on Charmhub

- README.md
This commit adds and example on how to use the Prometheus charm
to add a scrape target and also changes the link from upstream
Prometheus docker image to Canonical Prometheus Rock.
> Updated Readme with example and Rocks

- lib/charms/prometheus_k8s/v1/prometheus.py
- tests/test_provider.py
There is no key named "rel_id", and this will always result in a KeyError. Remove the quotes so lookups work as expected
> Remove spurious quotes when relations are broken

- lib/charms/prometheus_k8s/v1/prometheus.py
- src/charm.py
- tests/test_consumer.py
- tests/test_provider.py
This PR fundamentally changes the structure of the Prometheus charm library. This is a breaking change because the two methods `add_endpoint()` and `remove_endpoint()` have been removed. Instead the `PrometheusProvider` now scrapes each unit of the `PrometheusConsumer` without being told explicitly which are the scrape endpoints. However it is still possible to configure the metrics path and port for each consumer charm. Future PR's will elaborate further on this configurability. 
These changes were necessitated because of requirement to provide per unit scrape labels. In particular the requirement to provide a different unit name label for each consumer unit.
> Juju topology

- lib/charms/prometheus_k8s/v0/prometheus.py
- tests/test_provider.py
This commit adds a few additional test cases and ensures that there is a default value for all fields of each scrape job.
> A few additional provider test cases

- src/prometheus_server.py
There are situations in which Prometheus is not ready yet that will not return valid JSON (and may return actually an empty response body).
This commit adds error handling for invalid JSON in the response returned by the `api/v1/status/buildinfo` endpoint.
> Defensively parse JSON in build_info

- src/charm.py
This commit fixes a typo that crept in during review changes for
the last PR. In changing the file path glob for alert rule files
to use os.path.join the enclosing brackets were acidentally removed.
> Fix missing brackets for alert rule file glob

- tests/test_charm.py
- tests/test_provider.py
This commit removes leader setting from charm unit tests
since they are no longer required. These settings were
carried over from the older pod spec version of the charm
where only the leader could set a pod specification.
Closes #85
> Remove redundant leader setting from charm unit tests

- .github/workflows/run_tests.yaml
- .gitignore
- CONTRIBUTING.md
- requirements.txt
- tox.ini
This commit creates a simple tox configuration to run unit tests.  This
commit also changes the github worklow to use tox as the test runner.
These changes are in preparation for adding integration tests which
will also be run using tox.
> Added a basic tox configuration

- lib/charms/prometheus_k8s/v0/prometheus.py
Prometheus alert rules are found in a named directory, this change adds
the option to override that path in the PrometheusConsumer class should
a charm need it.
> Add optional override for rules path

- lib/charms/prometheus_k8s/v0/prometheus.py
This commit changes the default location of the Prometheus alert rules built into charms from `<repo_root>/prometheus_alert_rules` to `<repo_root>/src/prometheus_alert_rules`.
This change simplifies the user experience with charmcraft 1.2.0+, as it avoids the need of having to explicitly mark the rule files in `charmcraft.yaml` with [`charm/prime`](https://juju.is/docs/sdk/charmcraft-config).
> Move default alert rules dir to src/prometheus_alert_rules

- lib/charms/prometheus_k8s/v0/prometheus.py
The Prometheus library needs to observe events.relation_changed as well
as events.relation_joined, in order to trigger the correct relation data
changes in PrometheusConsumer.
> Add observe for events.relation_changed

- requirements-dev.txt
- requirements.txt
- src/charm.py
- src/prometheus_server.py
- tests/test_charm.py
- tests/test_server.py
- tox.ini
In case the configuration of Prometheus changes, but not its startup command, there is no reason to restart the process: we already activate the Web API to trigger the hot reload of configurations from file, and this commit adds support for it in `PrometheusServer`, and its triggering when we detect and configuration reload that would create the same layer as the existing one in terms of startup commands.
Closes #36
> Implement reload of configurations rather than Prometheus restart

- requirements.txt
- src/charm.py
- src/kubernetes_service.py
- tests/test_charm.py
- tests/test_kubernetes_service.py
Hook into the charm's `install` and `upgrade_charm` hooks the patching of the K8s service, so that we get the following awesomeness:
```
michele@boombox:~/git/prometheus-operator$ microk8s.kubectl get services -n prometheus-test
NAME                   TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)     AGE
modeloperator          ClusterIP   10.152.183.212   <none>        17071/TCP   18m
prometheus-endpoints   ClusterIP   None             <none>        <none>      13m
prometheus             ClusterIP   10.152.183.88    <none>        9090/TCP    77s
```
> Patch K8s service to list port 9090

- lib/charms/prometheus_k8s/v0/prometheus.py
- src/charm.py
- tests/bad_alert_expressions/missing_expr.rule
- tests/prometheus_alert_rules/cpu_overuse.rule
- tests/prometheus_alert_rules/target_missing.rule
Instead of expecting singleton rules in a `*.rule` file, simply expect the alert_rule object.
Also, add more logging for alert rules and ensure that the reload of alert_rules is triggered on alert reload.
(Pending: Avoid unnecessary rule reloads)
Closes #103
> Improve structure and documentation of *.rule files

- src/charm.py
- tests/test_charm.py
The command line switch for web.external-url needs to be set without the application name in the path.
> Correct external_url path

- src/charm.py
- tests/test_charm.py
- tests/test_endpoint_consumer.py
- tests/test_endpoint_provider.py
- This commit fixes a typo that crept through a recent pull request. The typo resulted in a bug because the name of consumer object was not correct.
- This commit also address the fact that this bug silently passed through all unit tests. This was because the relevant parts of code were guarded by a inappropriately used `prometheus_ready` check that was not being triggered. This check is obsolete since the reversal of roles of provider and consumer and now has been removed.
- This commit also refactors the code that switches between reloading and restarting Prometheus following the example of Juju SDK docs.
> Fix incorrect consumer name and silent test

- charmcraft.yaml
- config.yaml
- lib/charms/prometheus_k8s/v0/prometheus.py
- metadata.yaml
- pyproject.toml
- src/charm.py
- src/kubernetes_service.py
- src/prometheus_server.py
- tests/test_charm.py
- tests/test_endpoint_consumer.py
- tests/test_endpoint_provider.py
- tests/test_kubernetes_service.py
- tests/test_server.py
- tox.ini
This PR implements a `pyproject.toml` file to seperate out tool config and test env definitions. In the first commit, these changes are completed.
In the second commit, minor adjustments to docstrings, whitespace and variable names are made to ensure the code is compliant with the selected linting rules.
> Use pyproject.toml, simplify tox.ini

- lib/charms/prometheus_k8s/v0/prometheus.py
This pull request removes any dependence on `ops.relation` and updates the docs.
> Remove provider consumer

- CONTRIBUTING.md
The `CONTRIBUTING.md` has an incorrect filename for the default name of the packed charm when using later versions of `charmcraft`.
> Update CONTRIBUTING.md - fix packed charm filename

- CONTRIBUTING.md
- README.md
- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
- src/charm.py
- tests/test_endpoint_aggregator.py
- tests/test_endpoint_consumer.py
- tests/test_endpoint_provider.py
A recent convention has been adopted to ensure charm library
names have the same name as the interface the service. This
commit ensures that Prometheus charm library confirms with
this convention.
> Rename prometheus library same as interface name

- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
- src/charm.py
- tests/non_standard_prometheus_alert_rules/odd.rule
- tests/test_endpoint_provider.py
Remove a lot of setup overhead for the charm author that wants to use the `MetricsEndpointProvider` object:
* Avoid the need in most use-cases to specify the relation  with the `prometheus_scrape` the charm provides.
In virtually all cases, there will be exactly one such relation, so we can identify it with introspection of the Charm `meta` information.
* Get rid of the `service_event` parameter: this argument has been introduced to work around a Juju quirk about not having a good way of getting the Pod IP address on K8s, which can be reliability be accessed when a workload container has a `pebble_ready` event.
This commit removes the `service_event` entirely, and uses charm `meta` introspection to discover which workload containers are available, and register the update of the unit ip on …
> Prometheus scrape lib streamline

- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
This commit ensures that the default alert rules path is
in the charms "src" folder. A previous commit accidentally
changed this to the charms top level directory.
This commit also updates the library commit ID since the
library needs to be republished ASAP.
> Default alert rules path is in src folder

- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
- tests/unit/prometheus_alert_rules/cpu_overuse_no_labels.rule
- tests/unit/test_endpoint_provider.py
This PR fixes a bug introduced in #149:
`rule.get("labels", {}).update(topology.as_dict_with_promql_labels())` won't update `rule` if `"labels"` is not in there - the new empty dict is not referenced by `rule`.
```python
>>> d = {}; d.get("labels", {}).update(k="v"); print(d)
{}
>>> if "labels" not in d:
...     d["labels"] = {}
... 
>>> d["labels"].update(k="v"); print(d)
{'labels': {'k': 'v'}}
>>> 
```
> fix in-place dict update

- tox.ini
Recent changes to the main branch of python-libjuju [introduced a regression](https://github.com/canonical/prometheus-operator/runs/4148835885?check_suite_focus=true).
```
INFO     pytest_operator.plugin:plugin.py:235 Adding model github-pr-8b3ef:test-charm-meps
ERROR    asyncio:base_events.py:1707 Task exception was never retrieved
future: <Task finished name='Task-30' coro=<Connection._pinger() done, defined at /home/runner/work/prometheus-operator/prometheus-operator/.tox/integration/lib/python3.8/site-packages/juju/client/connection.py:502> exception=Exception('No facade Pinger in facades {}')>
Traceback (most recent call last):
File "/home/runner/work/prometheus-operator/prometheus-operator/.tox/integration/lib/python3.8/site-packages/juju/client/connection.py", line 516, in _pinger …
```
> use python-libjuju from pypi

- .github/workflows/ci.yaml
current configuration duplicates as prs will get counted twice (once for push, once for pr). this way, it will only run on pushes to main in addition to all pull requests
> only run for push events on main

- metadata.yaml
Resource definition is needed in charm metadata to be able to push resource to charmhub for usage in integration test. The actual logic for it will be added in a subsequent PR in `feature/promql`
> add promql transform resource

- tox.ini
This commit Python libjuju is used from github because of a
bug in Model.reset() method which has been fixed in github
but not in the current released version.
> Use python-libjuju from github

- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
A previous commit introduced a bug in accessing the charm name
relation data key in the Juju Topology object.
This commit fixes the issue.
> Fix incorrect charm name key in Juju topology object

- CONTRIBUTING.md
- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
- pyproject.toml
- requirements.txt
- src/charm.py
- tests/unit/helpers.py
- tests/unit/prometheus_alert_rules/nested_rules_dir/cpu_overuse.rule
- tests/unit/test_endpoint_consumer.py
- tests/unit/test_endpoint_provider.py
- tox.ini
This PR proposes the following changes to add support for official format (`groups:` etc.) in addition to lma-format (`alerts:...` level only):
> add support for dual rules format

- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
This commit replaces the mutable default argument by a sentinel.
Mutable defaults are potential bugs. Though this bug does not
manifest in the charm constructor since it is invoked only once
in each process, the commit never the less removes it as a good
practice.
Closes: #113
> Remove mutable default job list

- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
Remove a replacement of the `/` character with `-` in the label _value_ for the `juju_unit` topology label that breaks correlation with other datasources like Loki.
> Avoid mangling unit name in juju_unit value

- tests/integration/helpers.py
- tests/integration/test_upgrade_charm.py
This PR adds an integration test for upgrading from an edge release to the current source release.
TODO:
> add charm upgrade itest

- tests/integration/test_alternative_images.py
- tests/integration/test_charm.py
- tests/integration/test_prometheus_tester.py
This PR splits the single itest file into multiple files.
Possibly coincidentally, but with this fix all itests passed 4 times in a row
https://github.com/canonical/prometheus-k8s-operator/actions/runs/1664209651
Fixes #193
> Split the single itest file into multiple files

- lib/charms/prometheus_k8s/v0/prometheus_remote_write.py
It still had `prometheus-remote-write`, not `receive-remote-write`,
which is the correct name for the relation.
> Fix the prometheus_remote_write docstrings

- lib/charms/prometheus_k8s/v0/prometheus_remote_write.py
- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
- src/charm.py
Discussion takes place in #206. Discussion is a continuation of [these comments](https://github.com/canonical/prometheus-k8s-operator/pull/205#discussion_r787556937) from a previous pull request.
(At the moment I think this should not be merged and the None kept.)
Fixes #206
> Change return type of _remote_write_address to strictly string

- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
This PR removes an "is not empty" guard before updating relation data with alerts.
This is needed for when a relation is removed, or in git-sync when config changes.
This change also guarantees there will always be a "alert_rules" key in relation data.
> allow emptying out alerts

- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
- tests/unit/helpers.py
- tests/unit/test_prometheus_rules_provider.py
This PR adds a private method for refreshing (re-initializing) relation data for alerts.
This is needed for cos-config to be able to refresh alerts when alerts show up on disk after the last hook fired.
cf. https://github.com/canonical/loki-k8s-operator/pull/76, https://github.com/canonical/grafana-k8s-operator/pull/53
> add private method to reinitialize alerts

- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
- tests/unit/prometheus_alert_rules/nested/target_missing.rule
- tests/unit/test_endpoint_aggregator.py
- tests/unit/test_endpoint_consumer.py
- tests/unit/test_endpoint_provider.py
Ensure that missing scrape labels do not raise exceptions.
Significantly rework `JujuTopology` so the generation of labels (whether as a dict or as a string) dynamically cull from `as_dict`, and add an optional argument to `as_dict` to replace values. Realistically, the entire variable should just be renamed so this isn't necessary, but keep the API the same for now in case.
Branch out and add additional Providers for `Aggregator` and `Provider` which implementing only trivial methods needed for differing functionality.
Ensure that missing `scrape_metadata` does not blow up the relations.
For now, keep the API and labels the same, but this will have a followup which *properly* sets `scrape_metadata`, even as a partial key with a validator, so the Juju `model` and `model.uuid` are …
> Refactor JujuTopology and fix `scrape_metadata`

- lib/charms/prometheus_k8s/v0/prometheus_remote_write.py
- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
- tests/integration/test_remote_write_avalanche.py
Merge in the classes/changes in JujuTopology and AlertRules. Also
ensure that `PrometheusremoteWriteProvider.alerts()` handles missing
metadata in the same way as `prometheus_scrape`
Bring `LIBPATCH` back down to 1. This hasn't been published yet,
and Charmcraft requires that LIBPATCH numbers go sequentially, with
no missing numbers allowed.
> Bring prometheus_remote_write up to speed

- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
This commit updates Prometheus library doc strings in anticipation
of changes to be merged in the beta release, in particular the
deprecation of Juju topology stubs in favour of automagic
topology labeling for alert rules using the PromqlTransformer
object.
> Updating Prometheus library docs strings

- .gitignore
- CONTRIBUTING.md
- lib/charms/prometheus_k8s/v0/prometheus_remote_write.py
- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
- metadata.yaml
- tests/unit/prometheus_alert_rules/cpu_overuse.rule
- tests/unit/prometheus_alert_rules/cpu_overuse_no_labels.rule
- tests/unit/prometheus_alert_rules/target_missing.rule
- tests/unit/prometheus_alert_rules/with_template_string.rule
- tests/unit/test_endpoint_consumer.py
- tests/unit/test_endpoint_provider.py
- tests/unit/test_remote_write.py
- tests/unit/test_transform.py
- tox.ini
This PR adds support for injecting label-matchers to promql expressions at runtime. Currently, this is implemented for alert rules, which are injected with the juju topology, replacing the previous relabeling mechanics of jinja with actual promql parsing and validation.
There are a couple of issues with the current promql-transform binary which are tracked in that repo:
- https://github.com/canonical/promql-transform/issues/1
- https://github.com/canonical/promql-transform/issues/2
Still left todo:
> add support for injecting label-matchers at runtime

- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
- pyproject.toml
- tests/unit/test_endpoint_consumer.py
Sync up this library, too. It was missed in the initial proxy work, and resurrecting it from git reflow was not fun.
Essentially, add a public method to invoke building a scrape target, and add the ability to add custom fields to the scrape job.
> Add the changes NRPE exporter needs to prometheus_scrape

- lib/charms/prometheus_k8s/v0/prometheus_remote_write.py
- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
- tests/unit/test_prometheus_rules_provider.py
Since the introduction of the dual rule format (#161 - one rule per file as well as groups of alert rules), two file extensions emerged: `.rule` and `.rules`.
This PR adds `.rule` to the files being globbed and loaded from disk.
> Load both .rule and .rules files

- src/charm.py
- tests/unit/test_charm.py
This commit ensures that metrics labels from the provider are not
overriden by Prometheus. Since the honor labels attribute for all
jobs is enfored by the MetricsEndpointConsumer it can not itself
be overriden by any MetricsEndpointProvider.
> OPENG-588: Do not override provider metrics labels

- src/prometheus_server.py
This PR fixes #228 
The `ReadTiemout` exception was not catched
---
~~To reload Prometheus configuration we were using `response = post(url, timeout=self.api_timeout)`. This is nice and simple but the problem is that networks are unreliable or even Prometheus is under heavy load and cannot respond before `self.api_timeout`.
So it's a good idea to wrap these network calls with retries to avoid "false negatives" .~~ 
~~Now we are using the `Session` and `Retry` objects from the `request` module, with the following [retry setup](https://urllib3.readthedocs.io/en/latest/reference/urllib3.util.html?highlight=Retry#urllib3.util.Retry):~~
~~- retries: 5~~
~~- backoff_factor: 0.1~~
~~- _A backoff factor to apply between attempts after the second try (most errors are resolved immediately by a …
> Catch uncaught exception

- src/charm.py
- src/prometheus_server.py
- tests/unit/test_server.py
Ensure that, if an ingress is related over the `ingress` relation, if we need to set the `--web.route-prefix` argument, we correctly take it into account for the requests that we issue to Prometheus, e.g., to reload the configurations.
> Adjust reload API calls to Prometheus when ingress is related

- RELEASE.md
- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
This commit refines tow aspects of the charm documentation
1. The charmcraft command to publish the charm is now explicitly
specified.
2. An advisory on how the select a scrape job name for use with
the prometheus_scrape interface has now been added.
> Updated release and scrape job name documentation

- src/charm.py
- tests/unit/test_charm.py
- tests/unit/test_remote_write.py
Use hostname instead of IP address to avoid issues with pod churn. Also, make sure we update remote write to use this on charm upgrade.
QA: no specific steps here other than just that Prometheus generally works.
> Use hostname instead of IP address

- config.yaml
The current description of `web_external_url` caused doubts in one of our devs, so it is likely to cause the same or more in others.
Improved the configuration description.
N/A
Grab a random colleague, let them read the new config description and ask them if it is likely to make sense to someone not well-versed in Prometheus.
* Clarified the expected value for the `web_external_url` configuration option to point to the root of the Prometheus Web API, rather than one HTTP endpoint like the one for remote-write
> Clarify the expected value of the web_external_url config option

- lib/charms/grafana_k8s/v0/grafana_source.py
- lib/charms/traefik_k8s/v0/ingress_per_unit.py
- src/charm.py
- tests/unit/test_charm.py
Previously, `GrafanaSourceProvider` assumed that a bare `{host}:{port}` would be sufficient as a condition, but Prometheus, when `web.external-url` is set, also changes all web entrypoints to subpath routing. The majority of the work here happened in Grafana, but some changes were necessary to actually get the values from Prometheus in.
Instantiate `GrafanaSourceProvider` with `_external_url`.
Easy way to check: use the explore tab of Grafana to query Prometheus data. If it does not work, you’ll be told by Grafana that there are “Bad gateway” issues.
Make sure Traefik is in Active status (https://github.com/canonical/traefik-k8s-operator#setup), otherwise it does not pass URLs to Prometheus and you are not testing much.
Also try to change a few times, back and forth, the routing_mode …
> Make sure that ingress works flexibly with `GrafanaSourceProvider`

- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
clarify what some of the allowed settings are supported by the `prometheus_scrape` library, but should not be used directly by charmers.
More docu.
We have seen PRs for charms like Kubeflow exposing config options for scrape-interval that should not be exposed directly by their charms.
N/A
Provide guidance in terms of which Job settings should be used by charmers integrating the library, and which not.
> Explain rationale for not using some prometheus scrape settings in charms

- lib/charms/prometheus_k8s/v0/prometheus_remote_write.py
- pyproject.toml
- tests/unit/prometheus_alert_rules/with_template_string_and_unit.rule
- tests/unit/test_endpoint_provider.py
- tests/unit/test_remote_write.py
Update the remote write library with various improvements.
There are two significant issues that this addresses:
* Alert rules do not get propagated from the workload charm, through grafana-agent, to prometheus
* Alert rules get `juju_unit` added to the expression and the labels
* Make sure to only modify an alert rule if it has not already been modified
* Use the same updated JujuTopology class that prometheus_scrape uses
1. Deploy prometheus, grafana-agent (remote_write_2 branch), and a workload (cassandra, spring-music, etc.)
2. Relate prometheus->grafana-agent->workload
3. Ensure alert rules from workload are present and labeled correctly (no unit)
4. Ensure metrics are present and labeled correctly (optionally relate prometheus to grafana)
5. Michele style tests
* Overhaul of …
> remote_write_2

- lib/charms/prometheus_k8s/v0/prometheus_remote_write.py
- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
resolves #235 
Switches from the string formatting syntax `{}` to the logging formatting syntax `%s`.
N/A
Run the reproducer in #235 on the PR
Fixes a string templating issue in the promql injector logs
> fix string templating

- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
- tests/unit/test_endpoint_provider.py
#104
Set relation data as part of `leader_elected`
General broken or not.
Fixed a bug where alert rules are sometimes not set
> set relation data on leader elected so alert rules are properly set

- lib/charms/prometheus_k8s/v0/prometheus_remote_write.py
- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
- tests/unit/test_endpoint_consumer.py
Various alert rules checks currently emit terrifying-looking warning messages on every invocation of charms, even when "must provide alert rules" is not a requirement.
Closes #266 
Use logger.debug instead
Deploy. Make sure there aren't scary warning logs if alert rules aren't present.
Don't emit  warning logs during normal operation
> Don't emit a bunch of warning logs during normal operation

- src/charm.py
- tests/unit/test_charm.py
The validator in `prometheus-k8s-operator` to determine what was and was not a valid date for the purposes of configuration had an unclear alignment with what was actually accepted. Updated it to reflect Prometheus.
Closes #128 
The [duration must be greater than 0](https://github.com/prometheus/prometheus/blob/c40e269c3e514953299e9ba1f6265e067ab43e64/promql/parser/parse_test.go#L2045), which is actually sort-of at adds with the [actual regex](https://github.com/prometheus/common/blob/627089d3a7af73be778847aa577192b937b8d89a/model/time.go#L186). Except that [prometheus overtly checks for a return value of 0 (ok from the parser) and re-raises an error](https://github.com/prometheus/prometheus/blob/5a754bc043b8e8c2d57cf906386734a73761e2a2/promql/parser/parse.go#L633).
For the actual config, …
> Fix the duration validator so it matches what prom actually uses

- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
- tests/unit/test_endpoint_provider.py
In order to work around the fact that podspec charms don't actually emit any events we can keep tabs on, `prometheus_scrape` was blindly setting (and re-setting) it on every `update_status` and `config_changed` in order to catch it.
This potentially causes strain on the Juju controller with a large number of `MetricsEndpointProviders`.
Closes #269
Choose the correct event based on whether it's a sidecar (use `pebble_ready`) or other (use `update_status`).
If there are no containers at all, we no idea, so log a warning telling the author they should specify and choose `update_status`
Run the unit tests. Relate to a podspec charm and a sidecar charm and make sure it's sane.
Stop setting unit IP on every possible event and choose the right one instead
> Stop setting unit IP on every possible event and choose the right one instead

- lib/charms/prometheus_k8s/v0/prometheus_remote_write.py
- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
- tests/integration/test_remote_write_grafana_agent.py
- tests/unit/test_charm.py
- tests/unit/test_charm_status.py
- tests/unit/test_endpoint_provider.py
- tests/unit/test_remote_write.py
- tox.ini
`bind_address` sometimes returns None. Recently observed during load test.
Closes #251.
Crossref: [OPENG-785](https://warthogs.atlassian.net/browse/OPENG-785)
Use `socket.getfqdn` instead of `bind_address`.
NTA
Run integration tests.
Replace bind_address with fqdn.
> Use fqdn instead of bind_address

- .github/workflows/codeql-analysis.yml
- .github/workflows/pull-request.yaml
- .github/workflows/release-edge.yaml
- .jujuignore
- RELEASE.md
- config.yaml
- lib/charms/alertmanager_k8s/v0/alertmanager_dispatch.py
- lib/charms/grafana_k8s/v0/grafana_source.py
- lib/charms/traefik_k8s/v0/ingress_per_unit.py
- pyproject.toml
- requirements.txt
- src/charm.py
- tests/integration/test_charm.py
- tests/integration/test_cross_model_remote_write.py
- tests/integration/test_ingress_with_traefik_k8s.py
- tests/integration/test_kubectl_delete.py
- tests/integration/test_prometheus_scrape_multiunit.py
- tests/integration/test_remote_write_avalanche.py
- tests/integration/test_remote_write_grafana_agent.py
- tests/integration/test_upgrade_charm.py
- tests/unit/test_charm.py
- tests/unit/test_charm_status.py
- tests/unit/test_remote_write.py
We currently only set maximum retention time for our timeseries data, meaning we’re likely to run out of disk at some point. COS Lite, being treated as a lightweight appliance with resource constraints, should enforce a reasonable default maximum retention storage size as well. It should default to 80% of the PVC size.
Crossref: [OPENG-231](https://warthogs.atlassian.net/browse/OPENG-231)
Add maximum retention size config option.
NTA.
Run all tests.
Add maximum retention size config option.
> Add maximum retention size config option (in percent)

- actions.yaml
- src/charm.py
- tests/integration/test_check_config.py
Add an action to run `promtool check config` to tell users what may be wrong with their Prometheus configuration.
Closes #180 
Add an action to call `promtool`. This also requires checking `pebble.ExecError` if the returncode is not 0 (in case of failure) to populate the action results.
Run the tests. Or create a bad config and test the action
Add an action to check the prometheus config
> Add an action to check the prometheus config

- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
The current code incorrectly replaces the template with a bare comma instead of actually injecting the topology
> fix juju topology template substitution

- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
- tests/integration/helpers.py
- tests/integration/prometheus-tester/config.yaml
- tests/integration/prometheus-tester/src/charm.py
- tests/integration/test_deduplication.py
- tests/unit/test_functions.py
This is because duplicate job names cause errors in the prometheus config
https://github.com/canonical/prometheus-k8s-operator/issues/263
Append a hash to then end of each duplicate job name
Ensure that if duplicate job name or no job names are used, Prometheus does not crash.
Fixed an issue where duplicate job names were causing Prometheus to crash.
> Fix scrape jobs so that there are no duplicate job names.

- lib/charms/prometheus_k8s/v0/prometheus_remote_write.py
- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
- tests/unit/test_transform.py
the current call to `platform.processor` is not reliable and quite frequently returns `"unknown"`, for instance in the CI, or on arch linux. this patch replaces all occurrences with calls to `platform.machine` which should be way more reliable.
> replace processor call with machine call

- tests/integration/test_deduplication.py
closes #257 
This was previously fixed so I just added an integration test.
relate prometheus to an app then to the same app through prometheus-crape-config-k8s. Make sure it has not crashed.
Prometheus no longer fails when related to the same application twice.
> test that prometheus doesn't fail with the same charm related twice.

- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
- tests/unit/test_endpoint_provider.py
This commit ensures MetricsEndpointProvider uses bind_address
rather than socket.fqdn() by default and only falls back to
fqdn() if bind address is not valid. This change was made because
it was found that in some cases fqdn() did not return resolvable
addresses for example if MetricsEndpointProvider charm was in
a LXD could on localhost and MetricsEndpointProvider was on
a Microk8s cloud on the same host.
closes #329 
Sometimes `socket.fqdn()` does not return resolvable host names.
Use `bind_address` by default and fallback to `fqdn()` if `bind_address` is invalid.
Relating MetricsEndpointProvider charm to MetricsEndpointConsumer charm cross LXD and Microk8s clouds on localhost fails.
- Deploy a MetricsEndpointProvider charm in a LXD cloud on a host (say localhost0
- Deploy the …
> Metrics Provider uses bind address by default

- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
- tests/unit/test_endpoint_consumer.py
This commit ensures that Metrics Endpoint Consumer accepts
static scrape targets that do not have a port set.
closes #327
If a client charm does not set a port in the specification of a static scrape target it leads to an error because targets were hitherto expected to have the format `host:port`
Accept targets without port set in which case port is set to 80.
NA
- Deploy and relate a charm which does not specify port.
- Scrape targets need not specify port
> Allow static scrape targets without a port set

- src/charm.py
- tests/unit/test_charm_status.py
- tox.ini
The operator does not report the running version of Prometheus to Juju
Report version during the `_configure` hook, and also add an `update-status` handler to report the version on each `update-status` event
> Report Prometheus version correctly

- lib/charms/prometheus_k8s/v0/prometheus_remote_write.py
- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
- lib/charms/traefik_k8s/v1/ingress_per_unit.py
- src/prometheus_server.py
- tests/unit/test_charm.py
- tests/unit/test_endpoint_consumer.py
- tests/unit/test_endpoint_provider.py
- tests/unit/test_transform.py
(This PR was split out of #340.)
When the bundle is deployed, prometheus is in blocked status (loading config failed) because:
```
error validating: yaml: unmarshal errors:
line 4: field name not found in type rulefmt.RuleNode
line 5: field rules not found in type rulefmt.RuleNode
...
```
Apparently, when cos tool validation synthesized a tempfile to disk, it created incorrect nesting:
```yaml
groups:
- name: 5b372040-794c-4e2c-b040-16468d10039d
rules:
- name: cos-lite-load-test_7acf3bc5_loki_loki_request_errors_alerts
rules:
- alert: LokiRequestErrors
```
Note the double use of `name` and `rules`.
- return stdout as part of `_exec`, so that `.output` includes errors content
- add utest for validating baked-in alerts, as they appear in relation data
Using these changes is demonstrated in …
> Fix validation logic

- src/charm.py
- tests/unit/helpers.py
- tests/unit/test_charm.py
- tests/unit/test_charm_status.py
- tests/unit/test_remote_write.py
When using the api to get workload version we rely on `update_status`.
Use `/bin/prometheus --version`.
Deploy and check version is set without errors.
prometheus-k8s no longer relies on update_status to set workload version
> get workload version from the binary rather than the api

- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
- src/charm.py
- tests/unit/test_charm.py
Fixes #347.
Add keys to allowlist.
NTA
Manually deploy and relate this and the matching PR in [scrape-target](https://github.com/canonical/prometheus-scrape-target-k8s-operator/pull/21).
```bash
juju deploy ./prometheus-scrape-target-k8s_ubuntu-20.04-amd64.charm target
juju deploy ./prometheus-k8s_ubuntu-20.04-amd64.charm prom --resource prometheus-image=ubuntu/prometheus:2.33-22.04_beta
TARGET=$(juju controllers --format json | jq -r '.controllers.uk8s."api-endpoints"[0]')
CERT=$(openssl s_client -connect $TARGET -showcerts </dev/null 2>/dev/null | openssl x509 -outform PEM)
juju config target targets=$TARGET scheme=https metrics_path=/introspection/metrics basic_auth=user-prometheus:prom tls_config_insecure_skip_verify=true tls_config_ca_file=$CERT
juju relate prom target
PROM=$(juju …
```
> Add tls, basic_auth keys to allowlist

- lib/charms/prometheus_k8s/v0/prometheus_remote_write.py
- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
- src/charm.py
- tests/unit/helpers.py
- tests/unit/test_charm.py
- tests/unit/test_charm_status.py
- tests/unit/test_remote_write.py
Before this change, reload/restart could result in unnecessary down time. 
- Only restart if cli args changed
- Only reload if config changed
- Block if config is invalid
- Fix error + status messages
- Drive-by fixes
Fixes #342.
NTA.
Afaict, the feature is fully captured in the newly added utests. Please review those for completeness!
> Less frequent reloads and restarts

- tests/unit/helpers.py
- tests/unit/test_remote_write.py
* add method to automatically fetch` cos-tool` if it does not exist
* make `test_remote_write.py` invokation path independent.
* fix metadata, since two `requires` overlapped which caused overwritting
> Update test_remote_write tests

- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
- tests/unit/test_prometheus_rules_provider.py
Fixes #364
Add defensive check in AlertRules._from_file()
> Fix: don't crash on empty alert rules file

- lib/charms/catalogue_k8s/v0/catalogue.py
- lib/charms/landing_page_k8s/v0/landing_page.py
- metadata.yaml
- src/charm.py
This PR introduces a new relation interface called `catalog` for connecting Prometheus to a landing page. Over this relation, Prometheus provides an application entry, which then will be used by the landing page to display where users may go.
See https://github.com/canonical/landing-page-k8s-operator/ for the other end of this relation.
- Build a charm file from this PR branch
- Deploy the build output on Juju
- Deploy `landing-page-k8s` from `edge`
- Relate the two charms together
- Visit the landing page on port 80
Implement the `catalog` interface to allow for integration with `landing-page-k8s`.
> add new landing page integration

- src/charm.py
- src/prometheus_server.py
- tests/unit/test_charm.py
resolves https://github.com/canonical/prometheus-k8s-operator/issues/371
Make sure to observe update_status so Prometheus can be cleaned up.
Kill a Prometheus pod and make sure you get a waiting status (or active status) instead of blocked status.
fixed a bug where prometheus-k8s would go in to blocked status if it took too long to start
> Fix reload

- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
- tests/unit/test_endpoint_provider.py
- tests/unit/test_prometheus_config.py
With #370 implemented, now wildcard targets are expanded to individual jobs.
However, the provider's constructor currently takes a hostname rather than a url, and (ingress) path cannot be inferred.
Change the provider constructor to take a url. This is a non-breaking change because prometheus_scrape wasn't published since the `external_hostname` arg was introduced.
Depends on #370.
Afaict, existing utests and itest provide sufficient coverage.
Add support for a custom metrics path per unit.
> Metrics path per unit

- src/charm.py
- src/prometheus_server.py
- tests/integration/test_external_url.py
- tests/unit/helpers.py
- tests/unit/test_charm.py
- tests/unit/test_endpoint_consumer.py
- tests/unit/test_server.py
- tests/unit/test_web_external_url.py
- tox.ini
(Note: this PR was split out of #340.)
The self-scrape job is "down" when prometheus is related to traefik.The external hostname is not passed to prom_scrape constructor for the self-scraping endpoint.
Use external_url in constructing the self-scraping job.
Note: the quality of the solution in this PR is affected by https://github.com/canonical/traefik-k8s-operator/issues/78.
Deploy prom and relate to traefik. Then look at prom's `/api/v1/targets`.
Fix ingress usage.
> Fix ingress usage

- pyproject.toml
ops 1.5.3 was released yesterday with many important features, but it also causes the static CI to fail.
Add ops to mypy's ignorelist, for now.
> Do not static check against ops

- .gitignore
- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
- src/charm.py
- tests/unit/test_prometheus_config.py
Fixes #377.
Extract paths into the `path_prefix` config key.
Ingress.
- utests
- e2e: relate prom - alertmanager - traefik and make sure config is valid.
Correctly render alertmanager config when targets have path prefix
> Correctly render alertmanager config when targets have path prefix

- tests/integration/test_check_config.py
A brittle test [broke](https://github.com/canonical/prometheus-k8s-operator/actions/runs/3199023424/jobs/5224301841#step:5:1516) between merge CI and release CI of #379.
https://github.com/canonical/prometheus-k8s-operator/blob/72dc79c800a5408eb207ef43a7972502e22d4818/tests/integration/test_check_config.py#L63-L69
The key name for the action's return code changed (not sure where/how):
```diff
{
-    'Code': '0',
'error-message': '',
'result': 'Checking /etc/prometheus/prometheus.yml\n'
' SUCCESS: /etc/prometheus/prometheus.yml is valid prometheus '
'config file syntax\n'
'\n',
+    'return-code': 0,
'valid': 'True',
}
```
- The return code is not set by charm code, so remove it entirely from the assertions made.
- Modify test to be less dependent on the exact output of promtool.
NTA.
- …
> Fix brittle test

- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
- tests/unit/test_endpoint_provider.py
- #368: metrics endpoint is not updated to ingressed address after relating to traefik.
- Having the lib observe update-status by default would probably solve the issue, but user would have to wait for the update-status hook interval to elapse.
- Instructing the user to pass multiple refresh events to the MetricsEndpointProvider constructor would work only after https://github.com/canonical/traefik-k8s-operator/issues/78 is fixed, but also introduces additional friction for the user to remember to pass custom refresh events.
Call [`self._set_scrape_job_spec`](https://github.com/canonical/prometheus-k8s-operator/blob/0e410410da9dd6f64fbd63c2b35383ecc7d2b9cb/lib/charms/prometheus_k8s/v0/prometheus_scrape.py#L1577) in `__init__` to update app data every charm re-init.
Fixes #368.
Adds …
> Update metrics endpoint relation data every re-init

- src/charm.py
In case of a new leader election with IPU, the Catalogue address will not update (never set to refresh)
Add `leader_elected` to refresh_events
Update the catalogue when a new leader is elected
> Update the catalogue when a new leader is elected

- charmcraft.yaml
- src/charm.py
- tests/integration/test_prometheus_scrape_multiunit.py
- tests/integration/test_remote_write_grafana_agent.py
This PR addresses #388.
Moving things depending on `self.external_url` outside of the constructor, so they are not called on removing the application.
I moved the logic depending on `self.external_url` to a separate function and invoked that in `_configure()` instead of `__init__()`.  
This way, that code is executed in every part of the lifecycle except the removal.
> move external_url dependees out of constructor

- lib/charms/grafana_k8s/v0/grafana_dashboard.py
- lib/charms/grafana_k8s/v0/grafana_source.py
- lib/charms/observability_libs/v0/juju_topology.py
- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
- lib/charms/traefik_k8s/v1/ingress_per_unit.py
- pyproject.toml
- tests/unit/test_endpoint_consumer.py
- tests/unit/test_prometheus_config.py
- tests/unit/test_remote_write.py
Our current approach in "MetricEndpointProvider" of building everything with the object constructor is not very handy when the charm that instruments the `prometheus_scrape` library is related to an ingress (Traefik for example). 
Let's say we have this scenario:
```mermaid
flowchart LR
A[prometheus] ---|metrics-endpoint| B[loki]
B --- |ingress-per-unit| C[traefik]
```
And the following code in the loki charm.py:
```python
def __init__(self, *args):
...
external_url = urlparse(self._external_url)
scrape_jobs = [
{
"metrics_path": f"{external_url.path}/metrics",
"static_configs": [{"targets": [f"{external_url.hostname}:{external_url.port}"]}],
}
]
self.metrics_provider = MetricsEndpointProvider(
self,
jobs=self.scrape_jobs,
refresh_event=[
self.on.update_status, …
```
> add new public method update_scrape_job_spec

- lib/charms/prometheus_k8s/v0/prometheus_remote_write.py
- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
- tests/unit/test_prometheus_rules_provider.py
The official docs use yml:
- https://github.com/prometheus/prometheus/blob/main/documentation/examples/prometheus.yml
- https://github.com/prometheus/docs/blob/3fa139d3f3519940881bf535e295e83fe815e13c/content/docs/guides/query-log.md#recording-rules-and-alerts
- https://github.com/prometheus/docs/blob/512f28293efc7dba62c13dc6e9ea5247c39f27d4/content/docs/tutorials/alerting_based_on_metrics.md#alerting-based-on-metrics
And it's always nice that editors automatically pick the correct syntax highlighting.
Also take yml and yaml in addition to rule and rules extensions.
Fixes #396.
Since we no longer need the topology stub, we no longer need to differentiate COS rules from regular rules via extension.
Afaict, the augmented utest provides sufficient coverage.
Also take yml and yaml rule files.
> Also take yml and yaml rule files

- .github/workflows/pull-request.yaml
currently if you constantly push to the same branch, then CI runs for multiple commits in parallel
that is useless, we do not care about old commits in the same branch. Thus, we can cancel jobs and free up machine resources
we create a unique group that consists of workflow name and a branch name. If new commits are pushed to the same group, previous pipeline is aborted.
We can save hundreds of machine hours 
see:
https://docs.github.com/en/actions/using-jobs/using-concurrency#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow
> cancel jobs if new commit is pushed to the same branch

- tests/integration/test_external_url.py
There is no itest that proves #393 is fixed. 
Augment existing test to ensure units behind ingress-per-unit are reporting a correct path, resulting in an "up" status for all units. (In fact, we can convince our selves that this is the case from logs from previous PRs, for example [here](https://github.com/canonical/prometheus-k8s-operator/actions/runs/3499728279/jobs/5861612514#step:5:634).)
Fixes #393.
Afaict, #370 and #373 addressed #393 in full. (Perhaps this issue was encountered before fetch-lib?)
- Afaict, the `test_external_url` itest fully covers the issue.
- Deploy two units of prom, relate them to ingress and then relate them to another prom. Make sure the other prom's targets have the correct ingress-per-unit path, and that both jobs are "up".
Test fix: Make sure jobs for all …
> Test fix: Make sure jobs for all ingressed units are "up"

- src/charm.py
#404 was confirmed working locally, but only once... In a load test deployment, the link was still wrong even after that fix.
Add more refresh events.
Addresses https://github.com/canonical/catalogue-k8s-operator/issues/3.
1. Deploy the cos-lite bundle.
2. Make sure prom has the correct url.
Add more refresh events for catalogue.
> More refresh events for catalogue

- tests/integration/helpers.py
- tests/integration/test_remote_write_grafana_agent.py
- tests/integration/test_remote_write_with_zinc.py
- tox.ini
> move has_metric

- README.md
This PR fixes #413
> The readme is not consistent with the actual usage. When charmhub got rid of the Docs tab, the content from discourse was moved to the Descriptions tab, making it super confusing as it now contains TWO overviews with entirely different content. 
>
> We should
>  
> - Make sure the overview taken from the readme is up to date
> - Incorporate everything valuable from the `Docs - Overview` discourse post and then delete that post.
> - Incorporate everything valuable from the `Relations` discourse post and then delete that post.
>
> The readme is not consistent with the actual usage

- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
- tests/unit/test_endpoint_provider.py
`MetricsEndpointProvider` was, rather than setting its data on `relation_joined` and on `refresh_event`, clobbering the databag every time it ran, causing users to lose targets.
Don't do that. Listen to `relation_joined` and the refresh events. Events are there for a reason (to indicate that something changed), and if there is an ordering problem with even promulgation in constructors/libraries/etc, firing in-code events and/or [providing public methods to set the appropriate field](https://github.com/canonical/prometheus-k8s-operator/pull/397) has far less side effects.
Closes #427 
The steps in #427. Or deploy a dummy charm which instantiates the provider, sets a non-default scrape job spec, and makes sure it stays set after the next `update-status`, `config-changed`, or other event …
> Do not blindly set data every time anything happens

- src/charm.py
- tests/integration/helpers.py
- tests/integration/test_regression.py
- tests/integration/test_upgrade_charm.py
- tox.ini
- Incorrectly assumed that the charm uses controller storage, when in fact it was using local storage (see https://github.com/canonical/operator/issues/880)
- Config and alerts hash was originally intended to be written to controller storage, which is wrong because files wouldnt be written to container after an upgrade (because hash(relation-data) would match the hash in stored state).
- Do not use remote storage (remove `_stored`).
- Save hashes to container filesystem.
Fixes #399 
Fixes #414 
Fixes #418
NTA.
- See new tests.
- In a `prom --(self monitoring)-- prom` constellation, refresh one of the proms and make sure the config file, alert rules and scrape targets are as they were before the refresh (covered in itest).
Stop using remote storage.
> Stop using remote storage

- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
- tests/unit/test_endpoint_aggregator.py
Some LMA1 dashboards and workflows rely on the presence of a `dns_name` label, which is set by the `prometheus2` charm when a new target is received. After investigation, the remaining set of labels is a non-overlapping set, with no usable substitute available via relabeling.
Do hostname lookups, optionally. There are too many edge cases with trying to do this as a default, and not all workflows need this label. Behave the same way as the old charm -- if a lookup fails, set the name with the passed input/hostname anyway.
See [here](https://github.com/canonical/cos-proxy-operator/issues/32)
Allow optional (default false) DNS lookups for aggregator targets
> Allow optional (default false) DNS lookups for aggregator targets

- tests/integration/helpers.py
- tests/integration/test_external_url.py
- tests/integration/test_remote_write_grafana_agent.py
Don't always assume it's `microk8s`, it's not when strict.
> Find the uk8s group

- lib/charms/prometheus_k8s/v0/prometheus_remote_write.py
- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
- src/charm.py
- tests/unit/test_charm.py
- tests/unit/test_endpoint_consumer.py
- tests/unit/test_remote_write.py
Make `prometheus_scrape` and `prometheus_remote_write` use the same logic for alerts -- one which prioritizes the labels on alerts (if present) over metadata, since providing charms who use `AlertRules` will have them injected, and we shouldn't clobber them.
`prometheus_remote_write` already does this, but `prometheus_scrape` (and `loki_push_api`) would otherwise overwrite forwarded rules with possibly misleading/meaningless data.
Make all of the UUIDs in the tests valid.
Fix a couple of tests with the trimmed JujuTopology-style identifier, as it's always used now.
> Sync up the `alerts` method in the libraries

- src/charm.py
Resolves #455.
As suggested in the issue, change the remote-write-receiver flag to the newer one.
* pack and delpoy the charm
* `kubectl logs prometheus/0`
* verify the absence of the `warn` message described in the issue
Update the *remote-write enabling flag* from the deprecated one.
> correctly enable remote write flag

- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
Since automatic series cannot be relabeled with values from metrics. Read the endpoints to get them ourselves
Scrape endpoints ourselves so we can label automatic series
> Scrape endpoints ourselves so we can label automatic series

- src/charm.py
- tests/unit/test_charm.py
The [prometheus2](https://charmhub.io/prometheus2) machine charm supports injecting a TLS [client cert/key](https://git.launchpad.net/charm-prometheus2/tree/src/reactive/prometheus.py#n869) to use when scraping a given target.
This PR adds support for TLS client cert/key (`cert_file`/`key_file`) to the `tls_config` key.
Note: the [LXD charm](https://charmhub.io/lxd) uses that feature when related with `prometheus2` and we'd like to keep using it when related with `prometheus-k8s`.
Support TLS client authentication when scraping metrics.
> Add support for TLS client cert/key in `tls_config`

- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
`requests` may throw a `ConnectionResetError` when attempting to read the response inside a contextmanager, and we should also catch that. 
Ensure that all args are converted when logging. And trim the regexp down to only capture topology labels (for Grafana dashboards)
Catch more exception types, only capture 'juju_' labels to make execution faster
> Catch more exception types, only capture 'juju_' labels to make execution faster

- lib/charms/prometheus_k8s/v0/prometheus_remote_write.py
- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
- pyproject.toml
- src/charm.py
- src/utils.py
- tests/integration/test_prometheus_scrape_multiunit.py
- tests/integration/test_remote_write_grafana_agent.py
- tests/integration/test_resource_limits.py
- tests/unit/test_charm.py
- tests/unit/test_charm_status.py
- tests/unit/test_endpoint_consumer.py
- tests/unit/test_remote_write.py
- tests/unit/test_server.py
- tests/unit/test_web_external_url.py
- tox.ini
The **flake8** plugins we use are re-implemented in **ruff**, which is why they have been removed from the dependencies.
**isort** is enabled (and used when formatting) through the `I001` rule.
The "exclude list" has been updated to omit folders that **ruff** excludes by default.
Everything else is the same, the only difference being two new rules being ignored (which weren't checked before anyway): 
* `C901: Function is too complex`, which I excluded as we were not checking it before either (an eventual refactor should have its own PR);
* `RET504: Unnecessary variable assignment before return statement`, which we do everywhere as it increases readability.
> use ruff instead of flake8

- metadata.yaml
Prometheus docs on charmhub weren't rendered from discourse.
Add link to discourse.
Add `docs` entry pointing to discourse.
> Add `docs` entry pointing to discourse

- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
Scrape jobs that require a bearer token for authorization must provide it via the `authorization` configuration field, see https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config
Allow passing `authorization` field to the scrape jobs
This is required for properly defining scrape jobs in the MicroK8s charm, otherwise the bearer token gets dropped and the metrics endpoints cannot be scraped.
Pass a scrape job with a set `authorization` field. Did not see any existing unit tests for scrape job sanitization, so I did not go through the effort to add one.
Add authorization in the allowlist for scrape jobs configuration
> Add authorization to allowed scrape jobs keys

- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
`MetricsEndpointProvider` supports a callable function to generate the jobs dynamically. If no static jobs are set, the default scrape job is always added to the scrape jobs.
```
self._jobs = self._jobs if self._jobs else [DEFAULT_JOB]
```
Only return the default job if no static jobs and no lookaside jobs are defined
https://github.com/canonical/charm-microk8s/pull/88
I have assumed that the `[DEFAULT_JOB]` is just a default fallback, so I do not expect that it should be added in this case. Setting the jobs to an empty list is still adding the default job.
Do not add a default scrape job if there are lookaside jobs
> do not add default metrics if lookaside jobs not empty

- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
Tied to https://github.com/canonical/cos-proxy-operator/issues/72.
**The modified code is only used by COS Proxy.** While not entirely sure what this piece of code was supposed to do, it currently doesn't do anything (except failing).
What happens is that when COS Proxy defines a Prometheus scrape job (for Prometheus to scrape COS Proxy), we:
1. set the target to the NRPE endpoint;
2. relabel `__address__` so the scrape actually happens on COS Proxy instead.
However, the `_static_config_extra_labels()` function doesn't see the relabeling, and tries to scrape `<nrpe-endpoint>:5666/metrics`, which doesn't make sense as that's not an HTTP endpoint at all.
It seems like this part of code it's trying to get some topology information from somewhere (there are no metrics there), but it doesn't …
> fix prometheus library for cos-proxy

- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
- lib/charms/prometheus_k8s/v1/prometheus_remote_write.py
- tests/unit/test_endpoint_provider.py
- tox.ini
Partial progress on https://github.com/canonical/grafana-agent-k8s-operator/issues/190
Use the JujuTopology and AlertRules classes from cosl.
There should be no changes to the behavior of the libraries so I am not sure what testing should be done. Unit tests are passing.
Libraries now use upstream JujuTopology and AlertRules classes from cosl
> Cosl alerts

- src/charm.py
Fixes #506.
This likely happens when `_configure()` is called by something other than `_on_server_cert_changed` (e.g., a perfectly timed `update-status`), but when the certificate is already in relation data (or Prometheus has already been related through the `certificates` interface but the certificate is not ready yet).
Only add the `tls_server_config` for Prometheus if the certificate exists on the file sytstem.
The `_configure()` method is also called by `_on_server_cert_changed()`, which (sequentially) writes the cert to disk before calling `_configure()`. This means we don't risk skip adding the TLS configuration with this extra check.
It's pretty much a race condition, so it's hard to add a test for it. I guess trying to replicate the issue is something, though of course it doesn't …
> fix: only add TLS config if cert file has been written to disk

- tests/integration/test_remote_write_grafana_agent.py
- tests/integration/test_resource_limits.py
The grafana-agent itest fails in CI.
https://github.com/canonical/grafana-agent-k8s-operator/issues/245
Force grafana agent series to jammy.
See "Context" section in https://github.com/canonical/grafana-agent-k8s-operator/pull/242.
`tox -e integration -- -k test_remote_write_grafana_agent`
Force gagent series to jammy in itest.
> Force gagent series to jammy

- lib/charms/grafana_k8s/v0/grafana_dashboard.py
- lib/charms/tempo_k8s/v0/charm_tracing.py
- metadata.yaml
- src/charm.py
- tests/manual/bundle_1_tls.yaml
- tests/manual/bundle_2_e2e_tls.yaml
- tests/scenario/helpers.py
- tests/unit/test_remote_write.py
- tests/unit/test_tls.py
TLS config is written and workload restarted, before the cert is written to disk.
Depends on:
- https://github.com/canonical/prometheus-rock/pull/30 (https://github.com/canonical/oci-factory/pull/58)
Fixes https://github.com/canonical/prometheus-k8s-operator/issues/521
- Run itests in https://github.com/canonical/cos-lite-bundle/pull/80
- Manually test with the following bundles
```yaml
bundle: kubernetes
applications:
ca:
charm: self-signed-certificates
channel: edge
scale: 1
prom:
charm: ./prometheus-k8s_ubuntu-20.04-amd64.charm
series: focal
scale: 1
trust: true
resources:
prometheus-image: ghcr.io/canonical/prometheus:dev
relations:
- - ca:certificates
- prom:certificates
```
```yaml
bundle: kubernetes
applications:
ca:
charm: self-signed-certificates
channel: edge
scale: 1
cat: …
```
> Fix handling of tls config

- .github/workflows/update-libs.yaml
Prom's github actions list "Unknown event" instead of update-libs.
Per GitHub Support, need to push any change to the file.
> Attempt to fix update-libs failing with "(Unknown event)"

- tests/scenario/test_alert_expression_labels.py
Fixes canonical/grafana-agent-k8s-operator#190
Add a scenario test.
No need to test a test I think.
-
> Add test to ensure juju_charm not set

- config.yaml
- src/charm.py
the juju cos setup cannot receive data from the grafana-agent if the grafana-agent is not running inside juju.
Add a charm option to enable the remote `remote_write_receiver` feature even when no relation is established.
IoT devices cannot run juju due to resources constraint, so they must run grafana-agent snap standalone.
This way the COS stack can be used on servers and snaps can be used on devices to export data.
This is a draft PR as a suggestion as I am exploring the usage of COS for robots.
The PR is based on my recent learning of Juju/Charm and COS.
> feat: remote_write_receiver option

- src/charm.py
Closes: #543
Grafana assumes the scrape interval as 15s by default but COS stack assumes 1m. Without telling Grafana that COS Prometheus uses 1m as the global scrape interval, many graphs will break since $__rate_interval won't be calculated properly.
Hardcoding 1m itself is in question, but this patch fixes many graphs using $__rate_interval without touching the fundamental pieces.
ref:
https://grafana.com/docs/grafana/latest/datasources/prometheus/configure-prometheus-data-source/#interval-behavior https://grafana.com/blog/2020/09/28/new-in-grafana-7.2-__rate_interval-for-prometheus-rate-queries-that-just-work/ https://github.com/canonical/prometheus-k8s-operator/issues/544
Deploy the COS stack and grafana-agent machine charm and relate those. Open the node-exporter dashboard in Grafana …
> Grafana needs to know scrape_interval for $__rate_interval

- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
- tests/unit/test_charm.py
- tests/unit/test_endpoint_consumer.py
Fixes #551
Append the relation name and id to the alert rule file name.
Fix has been verified by @nobuto-m
Fixed an issue where two relations over different routes to the same application could cause alert rules to be dropped.
> Unique identifiers

- README.md
The links to the Prometheus Scrape/Config charms are empty; this PR adds them.
> Fix charm links in the README

- metadata.yaml
- tox.ini
Metadata point to ghcr latest.
Use dockerhub image, with major version
https://github.com/canonical/prometheus-rock/blob/main/2.49.1/rockcraft.yaml
> Update image to dockerhub, major version

- lib/charms/tls_certificates_interface/v2/tls_certificates.py
- src/charm.py
- tests/unit/test_charm.py
- tests/unit/test_charm_status.py
- tests/unit/test_remote_write.py
BlockedStatus from an invalid retention size config option was never cleared.
- Add a TypedDict for per-component status setting.
- Use the per-component status dict to set status centrally in `_configure`.
Fixes #560.
> Set ActiveStatus when retention size config option is valid

- charmcraft.yaml
- lib/charms/tempo_k8s/v1/charm_tracing.py
- lib/charms/tempo_k8s/v1/tracing.py
- pyproject.toml
- src/charm.py
- tests/unit/test_endpoint_consumer.py
- tox.ini
Prometheus charm grew significantly in size due to a new GRPC dependency introduced by tracing as noticed in #545. Because of that, we reconsidered the protocol used by tracing in canonical/tempo-k8s-operator#53 and decided to use OTLP/HTTP.
Switch to the new version of charm_tracing and use OTLP/HTTP(S) endpoints of tempo.
This PR implicitly bumps pydantic used by tracing to v2 which is a complete rewrite in Rust. Because rust compiler isn't found in `charmcraft pack` in this repo I needed to add pydantic to `charm-binary-python-packages`.
First run `charmcraft pack` to see that prometheus charm is now reduced back to 26MB.
Then, using the packed charm, use the following bundle:
```
bundle: kubernetes
applications:
alertmanager:
charm: alertmanager-k8s
channel: stable
revision: 96 …
```
> Update tracing to use OTLP/HTTP

- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
- tests/unit/test_endpoint_consumer.py
Closes #571.
Changing the order of the dictionaries to unpack makes sure that pre-exising labels have priority over the automatically-generated topology.
Modify a charm (e.g., blackbox) to specify a custom `juju_application` label; then relate it to two Prometheus instances (one without the fix, the other with the fix) and check the difference in the targets section.
Before:
After:
---
There is a **unit test** that explicitly checks that we *do* overwrite the topology labels (and it's aptly called `test_consumer_overwrites_juju_topology_labels`, in the file `tests/unit/test_endpoint_consumer.py`). I'm removing that test, since it doesn't really make sense with this PR :)
I would like another pair of eyes to confirm this PR is something we want to do!
> don't override existing labels in scrape jobs

- requirements.txt
- src/charm.py
ops<=2.12 wrongly has `self.config[x]` typed as `str`, when actually it could be an int, float, bool, or str, depending on the config type. We're fixing this in [ops:#1183](https://github.com/canonical/operator/pull/1183), but that will break static checking that currently assumes that the config is a str (because ops doesn't validate the schema, so all options will be bool|int|float|str).
Six `typing.cast` calls where the config values are loaded and used where the type should be str.
Covered above.
Run `tox -e static-charm` with/without the PR with ops 2.12 and with either the PR branch linked above or once that's merged ops main/2.13.
N/A
> fix: tell type checkers that the config options are strings

- README.md
- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
Before this PR, during the `santize` method for scrape config, we were keeping the wrong key: `metrics_relabel_configs` (`metrics` in plural). [The correct key](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#metric_relabel_configs) is `metric_relabel_configs` (`metric`, in singular).
As a result, we could not set `metric_relabel_configs` because it was being dropped by sanitation.
Remove the stray `s`.
In tandem with:
- https://github.com/canonical/prometheus-scrape-config-k8s-operator/pull/46
> Fix sanitation

- pyproject.toml
- tox.ini
* `codespell` started marking `assertIn` as an error
* `ruff` has been issuing deprecation warnings on its configuration format
* Configure `codespell` to ignore the word `assertIn` (and clean the tox environment a bit)
* Change the `ruff` configuration to the new format
> fix: codespell ignore and ruff deprecation warning

- src/charm.py
Closes #578.
Use `external_url` in Grafana Source.
> feat: use external_url in grafana source

- charmcraft.yaml
- src/charm.py
- tests/integration/test_prometheus_scrape_multiunit.py
- tests/integration/test_remote_write_grafana_agent.py
- tests/interface/conftest.py
- tests/scenario/conftest.py
- tests/scenario/test_server_scheme.py
- tests/unit/test_charm.py
- tests/unit/test_charm_status.py
- tests/unit/test_prometheus_client.py
- tests/unit/test_remote_write.py
- tests/unit/test_tls.py
- tox.ini
Closes #581.  
Closes https://github.com/canonical/alertmanager-k8s-operator/issues/206.
Not sure why we were using the `route_prefix` from the `self.external_url` (from ingress), but adding it to the `self.internal_url` (which is always the FQDN).
Use the external URL instead of the internal one.
Before:
After:
```bash
juju deploy alertmanager-k8s --channel=latest/edge alertmanager
juju deploy prometheus-k8s --channel=latest/edge prometheus
juju deploy traefik-k8s --channel=latest/edge traefik
juju relate prometheus:alertmanager alertmanager
juju relate prometheus:metrics-endpoint alertmanager
juju relate prometheus:ingress traefik
```
Anything that refreshes the Pebble plan will activate this change, so the upgrade should be seamless.
> fix: use external_url in alert source

- tox.ini
Unit tests failing with
```
collected 110 items / 2 errors
========================================================================================================================== ERRORS ===========================================================================================================================
___________________________________________________________________________________________________ ERROR collecting tests/unit/test_endpoint_provider.py ___________________________________________________________________________________________________
ImportError while importing test module '/code/prometheus-k8s-operator/tests/unit/test_endpoint_provider.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback: …
```
> test: fix deepdiff transient dep

- tests/integration/helpers.py
- tests/integration/test_workload_tracing.py
- tox.ini
This PR adds integration tests to test that internal workload traces from Prometheus are getting ingested to Tempo using both non-encrypted and encrypted (TLS) traffic.
> Add tests for workload tracing  

- lib/charms/grafana_k8s/v0/grafana_dashboard.py
- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
- lib/charms/prometheus_k8s/v1/prometheus_remote_write.py
First step in addressing https://github.com/canonical/grafana-agent-operator/issues/154
Allow charm authors to pass `forward_alert_rules=False` to both `MetricsEndpointProvider` (scrape) and `PrometheusRemoteWriteConsumer` (remote write).
When the flag is `True`, the alert rules information is simply not put in relation data.
Pack and deploy both this charm and grafana-agent from https://github.com/canonical/grafana-agent-operator/pull/252 , and test the new config option.
> feat: add support for disabling alert rules forwarding

- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
Prometheus needs a specific version of cosl, so we should reflect that in pydeps.
> fix pydeps version

- lib/charms/mimir_coordinator_k8s/v0/prometheus_api.py
- metadata.yaml
- src/charm.py
- tests/scenario/test_prometheus_api_integration.py
- tests/scenario/test_server_scheme.py
The Prometheus charm does not provide a way for other charms to consume its prometheus api for querying metrics (apart from the grafana-source interface, which is an opinionated interface specific to grafana consuming prometheus).
This PR uses Mimir's prometheus-api library to send Prometheus's API to other applications, enabling it to be consumed by other charms such as Kiali.  
This implementation is essentially identical to that of:
* [mimir-coordinator](https://github.com/canonical/mimir-coordinator-k8s-operator/pull/115) (except that PR both **implements** and uses the prometheus-api library)
Merge #685 before merging this
Automated tests cover everything changed here.  
No upgrade considerations
> feat: add prometheus-api lib, relation

- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
`cos-proxy` is failing unit tests because of this line.
This PR is needed because the failing unit tests are blocking the migration to CI v1 for cos-proxy.
> fix: deepcopy the generic alert groups in cos-proxy library

- terraform/README.md
- terraform/main.tf
- terraform/outputs.tf
- terraform/variables.tf
- terraform/versions.tf
There is currently no terraform module available for deploying Prometheus.
Add a terraform module
1. Clone repo
2. `terraform init`
3. `terraform apply -var="model_name=<MODEL_NAME>"`
Add terraform module for COS Lite flavor of Prometheus
> feat(terraform): add module for charm deployment

- src/charm.py
- tests/unit/helpers.py
- tests/unit/test_charm.py
- tests/unit/test_charm_status.py
- tests/unit/test_remote_write.py
- tests/unit/test_server_scheme.py
- tests/unit/test_tls.py
PR #719 attempts to block the charm when the disk space is below 1 GiB. For this purpose, it adds checks in the `pebble_ready` and `update_status` hooks which get the database location and use `shutil` to get its remaining disk size. However, the older unit tests which rely on Harness do not add a storage during test setup and as a result, they fail.
This PR uses the `harness.add_storage()` method to add a storage to the PrometheusCharm under test.
`tox -e unit` should pass (and it does).
> chore: add storage to unit tests

- charmcraft.yaml
- src/charm.py
- tests/unit/test_charm.py
There is sometimes confusion when data is retained for longer than intended in scenarios where the config value for `maximum_retention_size` is invalid, such as when it's not a percentage. In such cases, if there is a valid config value for `metrics_retention_time`, then that is applied.
Based on feedback receives by support:
- Makes this more clear in the charm configs
- Clarifies this in the status message: `Invalid retention size: Must be a number followed by '%', e.g. '80%', using retention time now`. To avoid having an overly long message, it changes the previous message from `Invalid retention size: Percentage string must be a number followed by '%', e.g. '80%'` to `Invalid retention size: Must be a number followed by '%', e.g. '80%', using retention time now`.
> chore: change status message when blocked due to invalid retention size

- terraform/versions.tf
Partially fixes:
- https://github.com/canonical/observability-stack/issues/97
Update the pin so that we do not force the provider to a specific minor version `0.14`.
I updated the Prometheus TF module from this branch in the COS Lite TF module and ran `terraform validate` to ensure it is compatible.
```hcl
module "prometheus" {
source             = "git::https://github.com/canonical/prometheus-k8s-operator//terraform?ref=fix/tf-pin"
}
```
```shell
observability-stack/terraform/cos-lite
❯ terraform providers
Providers required by configuration:
.
├── provider[registry.terraform.io/juju/juju] >= 0.20.0
├── module.ssc
│   └── provider[registry.terraform.io/juju/juju] >= 0.20.0
├── module.traefik
│   └── provider[registry.terraform.io/juju/juju] >= 0.14.0
├── module.alertmanager
│   └── …
```
> fix: Remove minor version pin
